config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "students#index"

  resources :students do
    resources :logs
  end
end

app/models/ability.rb
class Ability
  # Where are you utilizing cancancan? I've never used the gem personally and am interested.
  include CanCan::Ability

  def initialize(user)
    if user
      can [:read, :create, :update, :destroy], [Student], :user => user

      can :manage, Log, :student => { :user_id => user.id }
    else
    end
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :student
## love love love this. nice use of getting business logic in the model :+1:
  def get_face
    type_of_contact = self.type_of_contact
    if type_of_contact == "Positive"
      "/assets/happy-face.png"
    elsif  type_of_contact == "Negative"
      "/assets/sad-face.jpg"
    else
      "/assets/neutral-face.jpg"
    end
  end



end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :logs, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :students, dependent: :destroy
  has_many :logs, through: :students, dependent: :destroy 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied, with: :user_not_authorized

    private

      def user_not_authorized
        flash[:error] = "You don't have access to that student."
        redirect_to root_url
      end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :find_student
  # what does load and authorize do? How is the auth happening?
  load_and_authorize_resource :student
  load_and_authorize_resource :log, :through => :student

  def find_student
    @student = Student.find(params[:student_id])
  end

  def index
    if current_user
    @students = current_user.students
    else
    end
    # what does this do? comments!
    # authorize! :read, @students
  end

  def edit
    @log = Log.find(params[:id])
  end

  def update
    @log = Log.find(params[:id])
    @log.update!(log_params)
    redirect_to student_logs_path(@student)
  end

  def new
    @log = Log.new
  end

  def create
    @student.logs.create!(log_params)
    redirect_to student_logs_path(@student)
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy
    redirect_to student_logs_path(@student)
  end

  private
    def log_params
      params.require(:log).permit(:date_of_contact, :mode_of_contact, :type_of_contact, :contact_details)
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  load_and_authorize_resource
  before_action :find_student, only: [:show, :edit, :update, :destroy]

# make sure to put this method as a private method, as it stands now, find_student is an action that can be called.
# I do love that you're using callbacks in your controller though, this is great!
  def find_student
    @student = Student.find(params[:id])
  end

  def index
    if current_user
    @students = current_user.students
    else
    end
  end

  def new
    @student = Student.new
  end

  def create
    @user = current_user
    @student = @user.students.create!(student_params)
    redirect_to students_path
  end

  def edit
  end

  def update
    @student.update!(student_params)
    redirect_to student_logs_path(@student)
  end

  def destroy
    @student.destroy
    redirect_to students_path
  end

  private
    def student_params
      params.require(:student).permit(:first_name, :last_name, :date_of_birth, :address, :phone_number, :email_address)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeacherFAMConnect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//use.edgefonts.net/lato.js"></script>
</head>
<body>
  <header>
    <ul class="left">
      <li>
          <h1 id="logo">
            Teacher<span class="fam">Fam</span>Connect.
          </h1>
      </li>
    </ul>
    <ul class="right">
      <li>
        <% if current_user %>
          <h2>Signed in as: <%= current_user.email %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, id: "sign_in" %>
            <% else %>
              <%= link_to "Sign up page", new_user_registration_path, class: "sign_in", id: "sign_in" %> |
              <%= link_to "Log in page", new_user_session_path, class: "sign_in", id: "sign_in" %>
          </h2>
        <% end %>
      </li>
    </ul>
  </header>
  <%= yield %>
</body>
</html>

app/views/logs/_form.html.erb
<%= link_to student_logs_path(@student) do %>
  <span aria-hidden="true"><h4 class="nav">&laquo; Back</h4></span>
<% end %>

<div class="form_container">
  <%= form_for [@student, @log] do |f| %>
  <div class="form-group">
    <%= f.label :date_of_contact %>:
    <%= f.date_field :date_of_contact, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :mode_of_contact %>:
    <%= f.select :mode_of_contact, ["phonecall", "email", "in person", "note home", "other"] %>
  </div>
  <div class="form-group">
    <%= f.label :type_of_contact %>:
    <%= f.radio_button :type_of_contact, "Positive", :checked => true %> Positive
    <%= f.radio_button :type_of_contact, "Negative" %> Negative
    <%= f.radio_button :type_of_contact, "Neutral" %> Neutral
  </div>
  <div class="form-group">
    <%= f.label :contact_details %>:
    <%= f.text_area :contact_details, :cols => 50, :rows => 10, class: "form-control" %>
  </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/logs/edit.html.erb
<h3>Edit Log</h3>

<%= render "form" %>

app/views/logs/index.html.erb
<%= link_to students_path do %>
  <span aria-hidden="true"><h4 class="nav">&laquo; Back</h4></span>
<% end %>

<h3>
  <%= @student.first_name %> <%= @student.last_name %>'s Contact Logs
</h3>

<h5 class="text-center">
  <%= link_to "Edit Student", edit_student_path(@student) %>
</h5>

<div class="student_contact_info">
    <dl class="dl-horizontal">
      <dt>Date of Birth:</dt>
      <dd><%= @student.date_of_birth %></dd>
      <dt>Address:</dt>
      <dd><%= @student.address %></dd>
      <dt>Phone Number:</dt>
      <dd><%= @student.phone_number %></dd>
      <dt>Email Address:</dt>
      <dd><%= @student.email_address %></dd>
    </dl>
</div>

<div class="button_wrapper">
  <h4><button class="btn-lg btn"><%= link_to "Create a new log", new_student_log_path %></button></h4>
</div>

  <% @student.logs.each do |log| %>
  <ul class="list-group">
    <li class="list-group-item">
      <dl class="dl-horizontal">
        <dt>Date of Contact:</dt>
        <dd><%= log.date_of_contact %></dd>
        <dt>Mode of Contact:</dt>
        <dd><%= log.mode_of_contact %></dd>
        <dt>Type of Contact:</dt>
        <dd><%= log.type_of_contact %></dd>
        <dt>Contact Details:</dt>
        <dd style="width:60%"><%= log.contact_details %></dd>
      </dl>
    </li>
    <li class="list-group-item">
    <%= link_to "Edit Log", edit_student_log_path(@student, log) %>
    <%= link_to "Delete Log", student_log_path(@student, log), method: :delete %>
    <img src="<%=log.get_face%>" style="width:100%;">
    </li>
    </ul>
    <% end %>

app/views/logs/new.html.erb
<h3>New Log</h3>

<%= render "form" %>

app/views/students/_form.html.erb
<div class="form_container">
  <%= form_for @student do |f| %>
    <div class="form-group">
      <%= f.label :first_name %>:
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>:
      <%= f.text_field :last_name, class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label :date_of_birth %>:
      <%= f.date_field :date_of_birth, class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label :address %>:
      <%= f.text_field :address, class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label :phone_number %>:
      <%= f.text_field :phone_number, class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label :email_address %>:
      <%= f.text_field :email_address, class: "form-control"  %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/students/edit.html.erb
<%= link_to student_logs_path(@student) do %>
  <span aria-hidden="true"><h4 class="nav">&laquo; Back</h4></span>
<% end %>

<h3>Edit Student</h3>

<%= render "form" %>
<h5 class="text-left">
  <%= link_to "Delete Student", student_path(@student), method: :delete %>
</h5>

app/views/students/index.html.erb
<h3>My Class</h3>
<p class="text-center error">
  <%= flash[:error] %>
</p>

<div class="image">
  <img src="/assets/boy-reading.gif" id="boy">
</div>

<div class="button_wrapper">
  <h4><button class="btn btn-lg"><%= link_to "Add a New Student", new_student_path %></button></h4>
</div>

<div class="wrapper">
  <% @students.each do |student| %>
    <%= link_to (student_logs_path(student)) do %>
      <button class="student_info btn-info"><h4><%= student.first_name%> <%= student.last_name %></h4></button>
    <% end %>
  <% end %>
</div>

app/views/students/new.html.erb
<h3>Add a New Student</h3>

<%= link_to students_path do %>
  <span aria-hidden="true"><h4 class="nav">&laquo; Back</h4></span>
<% end %>

<p>
  <%= render "form" %>
</p>